tunnel: my-tunnel
# NOTE: Replace the credentials-file path if your Tunnel ID differs.
credentials-file: /Users/yok/.cloudflared/fad92815-0281-494f-8fb4-1daec7ca5c17.json

ingress:
  # Subdomain routing
  - hostname: app.wwoom.com
    service: http://localhost:5003
  - hostname: web.wwoom.com
    service: http://localhost:3010
  - hostname: api.wwoom.com
    service: http://localhost:8000
  # Default catch-all
  - service: http_status:404

# Optional: enable no-autoupdate for deterministic behavior in dev
no-autoupdate: true
